name: Build

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
                key: ${{ secrets.SSH_KEY }}
                known_hosts: ${{ secrets.KNOWN_HOSTS }}

          - uses: actions/checkout@v2
            with:
                fetch-depth: 0

          - name: Compile LaTeX document
            uses: xu-cheng/latex-action@v2
            with:
              root_file: talk.tex

          - name: Upload
            if: github.ref == 'refs/heads/master'
            shell: bash -l {0}
            run: |
                scp talk.pdf nnpdf@vp.nnpdf.science:~/WEB/validphys-reports/Cnw0iB46RCaAbsINyzFLwA==/talk.pdf
